# render.yaml

services:
  - type: web
    name: he-w2v-api # Changed the name slightly to maybe help avoid caching
    runtime: python
    plan: free
    region: oregon
    buildCommand: "./build.sh" # This is the simple, powerful change
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 10000"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: '3.11'
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: ADMIN_PASSWORD
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
