# render.yaml

services:
  - type: web
    name: hebrew-w2v-api
    runtime: python
    plan: free # Note: Free plan may be slow or time out during the large file downloads.
    region: oregon # Or your preferred region
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      echo "Build process started. This may take a while due to large model files..."
      # This next part runs the download function from your app.py at build time.
      # It's a clever way to ensure the files are ready when the server starts.
      python -c "from app import download_model_files; download_model_files()"
      mkdir -p data # Ensure the local backup directory exists
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: '3.11'
      - key: PYTHONUNBUFFERED
        value: '1'
      # --- IMPORTANT ---
      # These are the secret keys. We just list their NAMES here.
      # We will set the actual VALUES in the Render Dashboard.
      - key: ADMIN_PASSWORD
        sync: false # 'sync: false' tells Render not to show this value in future YAML syncs
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
