services:
  - type: web
    name: hebrew-w2v-api
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      echo "Downloading model files (Full Word2Vec)..."
      
      # Install gdown for better Google Drive downloading
      pip install gdown
      
      # Download model.mdl using gdown
      echo "Downloading model.mdl..."
      gdown "1T9tSdIm-8AEz0c6mJuFfLyBL75_lnsTU" -O model.mdl
      
      # Download model.mdl.wv.vectors.npy
      echo "Downloading model.mdl.wv.vectors.npy..."
      gdown "1z5n9L-2oS_YEh3qf-nkz3ugMM8oqpxGZ" -O model.mdl.wv.vectors.npy
      
      # Download model.mdl.syn1neg.npy
      echo "Downloading model.mdl.syn1neg.npy..."
      gdown "1uhu7bevYhCYZNLPdvupSuw_4X42_-smY" -O model.mdl.syn1neg.npy
      
      echo "Model files download complete."
      echo "Listing files in current directory:"
      ls -la
      
      # Verify the main model file exists and has reasonable size
      if [ -f "model.mdl" ]; then
        file_size=$(stat -c%s "model.mdl")
        echo "model.mdl size: $file_size bytes"
        if [ $file_size -lt 1000 ]; then
          echo "ERROR: model.mdl seems too small! Content:"
          head -10 "model.mdl"
          exit 1
        else
          echo "model.mdl downloaded successfully"
        fi
      else
        echo "ERROR: model.mdl was not downloaded!"
        exit 1
      fi
      
      # Check other required files
      for file in "model.mdl.wv.vectors.npy" "model.mdl.syn1neg.npy"; do
        if [ -f "$file" ]; then
          echo "$file exists, size: $(stat -c%s "$file") bytes"
        else
          echo "WARNING: $file not found!"
        fi
      done
      
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: '3.11'
